name: Githuv actions secret example


on:
  push:
      branches: [ main ]
      
jobs:
    secrets-in-github-actions:
        runs-on: ubuntu-latest
        
        
        
        steps:
    
            - name: Step 1 - Echo out a Github Actions secret to the log 
              run: |

                 echo " The Github Actions Secret will be masked "
                 echo ${{ secrets.TOKEN_SECRET }}
                 echo " Trick to echo Github Actions Sercet "
                 echo ${{ SECRET_TOKEN }} | sed 's/./& /g'

    
